// Mocks generated by Mockito 5.4.5 from annotations
// in daily_flow/test/screens/add_edit_routine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:daily_flow/models/routine_item.dart' as _i5;
import 'package:daily_flow/providers/routine_provider.dart' as _i2;
import 'package:flutter_riverpod/flutter_riverpod.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:state_notifier/state_notifier.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [RoutineNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockRoutineNotifier extends _i1.Mock implements _i2.RoutineNotifier {
  @override
  set onError(_i3.ErrorListener? _onError) => super.noSuchMethod(
        Invocation.setter(
          #onError,
          _onError,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get mounted => (super.noSuchMethod(
        Invocation.getter(#mounted),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Stream<List<_i5.RoutineItem>> get stream => (super.noSuchMethod(
        Invocation.getter(#stream),
        returnValue: _i4.Stream<List<_i5.RoutineItem>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i5.RoutineItem>>.empty(),
      ) as _i4.Stream<List<_i5.RoutineItem>>);

  @override
  List<_i5.RoutineItem> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: <_i5.RoutineItem>[],
        returnValueForMissingStub: <_i5.RoutineItem>[],
      ) as List<_i5.RoutineItem>);

  @override
  set state(List<_i5.RoutineItem>? value) => super.noSuchMethod(
        Invocation.setter(
          #state,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i5.RoutineItem> get debugState => (super.noSuchMethod(
        Invocation.getter(#debugState),
        returnValue: <_i5.RoutineItem>[],
        returnValueForMissingStub: <_i5.RoutineItem>[],
      ) as List<_i5.RoutineItem>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> addRoutine(_i5.RoutineItem? routine) => (super.noSuchMethod(
        Invocation.method(
          #addRoutine,
          [routine],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateRoutine(_i5.RoutineItem? routine) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRoutine,
          [routine],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteRoutine(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteRoutine,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> toggleRoutine(String? id) => (super.noSuchMethod(
        Invocation.method(
          #toggleRoutine,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i5.RoutineItem> getTodayRoutines() => (super.noSuchMethod(
        Invocation.method(
          #getTodayRoutines,
          [],
        ),
        returnValue: <_i5.RoutineItem>[],
        returnValueForMissingStub: <_i5.RoutineItem>[],
      ) as List<_i5.RoutineItem>);

  @override
  List<_i5.RoutineItem> getUpcomingRoutines() => (super.noSuchMethod(
        Invocation.method(
          #getUpcomingRoutines,
          [],
        ),
        returnValue: <_i5.RoutineItem>[],
        returnValueForMissingStub: <_i5.RoutineItem>[],
      ) as List<_i5.RoutineItem>);

  @override
  bool updateShouldNotify(
    List<_i5.RoutineItem>? old,
    List<_i5.RoutineItem>? current,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateShouldNotify,
          [
            old,
            current,
          ],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.RemoveListener addListener(
    _i6.Listener<List<_i5.RoutineItem>>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
          {#fireImmediately: fireImmediately},
        ),
        returnValue: () {},
        returnValueForMissingStub: () {},
      ) as _i3.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
